def country_labels():
    """This function actually serves as an external database
    in order to replace country labels, as defined by Eurostat,
    with full country names.
    """

    label_dict = {"BE" : "Belgium",
    "BG" : "Bulgaria",
    "CZ" : "Czechia",
    "DK" : "Denmark",
    "DE" : "Germany",
    "DE_TOT" : "Germany with ex-GDR",
    "EE" : "Estonia",
    "IE" : "Ireland",
    "EL" : "Greece",
    "ES" : "Spain",
    "FR" : "France",
    "FX" : "Metropolitan France",
    "HR" : "Croatia",
    "IT" : "Italy",
    "CY" : "Cyprus",
    "LV" : "Latvia",
    "LT" : "Lithuania",
    "LU" : "Luxembourg",
    "HU" : "Hungary",
    "MT" : "Malta",
    "NL" : "Netherlands",
    "AT" : "Austria",
    "PL" : "Poland",
    "PT" : "Portugal",
    "RO" : "Romania",
    "SI" : "Slovenia",
    "SK" : "Slovakia",
    "FI" : "Finland",
    "SE" : "Sweden",
    "IS" : "Iceland",
    "LI" : "Liechtenstein",
    "NO" : "Norway",
    "CH" : "Switzerland",
    "UK" : "United Kingdom",
    "BA" : "Bosnia and Herzegovina",
    "ME" : "Montenegro",
    "MD" : "Moldova",
    "MK" : "North Macedonia",
    "AL" : "Albania",
    "RS" : "Serbia",
    "TR" : "Turkey",
    "UA" : "Ukraine",
    "XK" : "Kosovo*",
    "GE" : "Georgia",
    "AD" : "Andorra",
    "BY" : "Belarus",
    "MC" : "Monaco",
    "RU" : "Russia",
    "SM" : "San Marino",
    "AM" : "Armenia",
    "AZ" : "Azerbaijan"}

    return label_dict